version: 2.2.{build}
branches:
  only:
    - main
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu2004
configuration: Release
only_commits:
  files:
    - MassTransit/CloudEventify.MassTransit/**/*
    - Rebus/CloudEventify.Rebus/**/*
    - appveyor.yml
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"
build:
  publish_nuget: true
  verbosity: minimal
before_test:
  - docker login -u mriezebosch -p $DOCKER_TOKEN
  - az login --service-principal --tenant 3d4d17ea-1ae4-4705-947e-51369c5a5f79 -u 747fff68-4cd5-4750-9434-af423bccf25e -p $SPN_TOKEN
  - sudo wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash
  - dapr init --slim
after_test:
  - dotnet tool restore
  - dotnet stryker -f stryker-config/stryker.yaml --reporter cleartext --since=main
  - dotnet stryker -f stryker-config/stryker-rebus.yaml --reporter cleartext --since=main
  - dotnet stryker -f stryker-config/stryker-masstransit.yaml --reporter cleartext --since=main
  - dotnet stryker -f stryker-config/stryker-dapr.yaml --reporter cleartext --since=main
test_script:
  - dotnet test --collect:"XPlat Code Coverage"
environment:
  DOCKER_TOKEN:
    secure: Dj3j/X71ZSCnXP24pR/1fmGLBKUYFOeN7R9s+QioevmuSGjGzAGq19hIws1w4Csa
  SPN_TOKEN:
    secure: 5ruBbdXx8Yvg7mdIYuu6ol5xNTkBrC4oYB8+hbdaDC8spcp0sshzkzAozIq62NMk
for:
  -
    branches:
      only:
        - main
    environment:
      CODECOV_TOKEN: cdb952b9-902f-4d17-82d7-97d9bfea5e14
    after_test:
      - bash <(curl -s https://codecov.io/bash)
    deploy:
      - provider: NuGet
        api_key:
          secure: pZYKB9EWhp9ykhnd75dMBbnc96Ti/F3pWYyRVj/toW7HDNBCl2zd7Fnw+/JNDtyV
  -
    branches:
      only:
        - stryker
    test_script:
      - dotnet tool restore
      - dotnet stryker -f stryker-config/stryker.yaml --reporter dashboard --dashboard-api-key $STRYKER_DASHBOARD_API_KEY -c 4
      - dotnet stryker -f stryker-config/stryker-rebus.yaml --reporter dashboard --dashboard-api-key $STRYKER_DASHBOARD_API_KEY -c 4
      - dotnet stryker -f stryker-config/stryker-masstransit.yaml --reporter dashboard --dashboard-api-key $STRYKER_DASHBOARD_API_KEY -c 4
      - dotnet stryker -f stryker-config/stryker-dapr.yaml --reporter dashboard --dashboard-api-key $STRYKER_DASHBOARD_API_KEY -c 4
    after_test:
    environment:
      STRYKER_DASHBOARD_API_KEY:
        secure: U/GBzRmrQWN/DcKi9WKY/JY/mIRSQ0vuMly/RU9l/b0w0U4y171KvWL8283A8yao
